
model:
  desired_images: 10000
  num_bins: 5
  height: 720
  width: 1280
  base_channels: 64
  encoder_channels: 16
  rfb_blocks: 3
event_sim:
  Cp: 0.1
  Cn: 0.1
  refractory_period: 10
  sigma_threshold: 0.05
  cutoff_hz: 0
  shot_noise_rate_hz: 2
  max_frames: 15
  pause_probability: 0
  rotational_offset: 0.0
  translational_offset: 0.35
  max_optical_flow: 2.0
  max_interp_frames: 20
  display: False
training: 
  type: "training"
  save_dir: "saved_model_output"
  epochs: 100
  batch_size: 16
  learning_rate: 0.0002
  learning_rate_reduction: 0.75
  learning_rate_epochs: 10
  lpips_net: 'vgg'
  num_workers: 2
  num_saves: 10
  

